[package]
name = "cryptology_for_beginners"
version = "0.1.0"
authors = ["rub09"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
